cc_test(
    name = "resolution_details_test",
    srcs = ["resolution_details_test.cpp"],
    deps = [
        "//src:resolution_details",
        "@googletest//:gtest_main",
    ],
)

cc_test(
    name = "noop_provider_test",
    srcs = ["noop_provider_test.cpp"],
    deps = [
        "//src:noop_provider",
        "@googletest//:gtest_main",
    ],
)
