cc_test(
    name = "resolution_details_test",
    # Path is relative to cpp-sdk/src/test/
    srcs = ["resolution_details_test.cpp"],
    deps = [
        # We reference the library defined in the parent 'src' package
        "//src:interfaces",
        
        # Google Test dependency remains the same
        "@googletest//:gtest_main",
    ],
)